Добавлено начало Домашнего задания 2
sponfin/admin-panel pull request #2
Opened 2022-03-17 09:06 UTC by sponfin

Все компоненты разбиты без CSS-module.

Компонент Input сделан с CSS-module. прошу проверить его.

2022-03-20 10:51 UTC, sponfin commented
Сделал модификаторы через classnames, при этом сократился код, т.к. не нужно проверки условий пропсов делать, как было изначально, но теперь не понятно как установить инпуту disabled, т.к. через CSS это вроде нельзя сделать.

2022-03-20 11:07 UTC, sponfin commented
Добавил свойство disabled у импута

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +import sprite from '../../sprite.svg';
import { ReactComponent as MyLogo } from './logo.svg';

const App = () => (
  <div id="App">
    <MyLogo />
  </div>
);

export default App;

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +      className={[styles.inputDate, styles.blockWrapper__inputDate].join(' ')}
``
cx({
[styles.inputDate]: true,
[styles.blockWrapper__inputDate]]: true,
})
``

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +      className={[styles.inputDate, styles.blockWrapper__inputDate].join(' ')}
cx({ [styles.input]: true, [styles.inputDate]]: true, })

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +      className={[styles.inputDate, styles.blockWrapper__inputDate].join(' ')}
cx(styles.inputDate, styles.blockWrapper__inputDate)
cx(styles.inputDate, {.styles.blockWrapper__inputDate: xxx })

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +        <input id="inputDate" className={styles.input} placeholder="Введите" />
id удалить

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Button/Button.jsx
> +        styles[
переделать на цсс модули

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Button/Button.jsx
> +          'button button_theme_main button_size_large button-group__button'
все классы динамические собирать через classnames пакет

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +    [styles.blockWrapper__inputDate]: true,
по БЭМ элемент оделяется с помощью __
цсс модули имя блока подствляют сами и это будет имя компонента
таким образом тут написано
Input__blockWrapper__inputDate – это не по БЭМ, потому что по БЭМ элемент элемента не указывается
Правильно так
Input__date

По БЭМ нужно называть сущности по сути
Инпут – блок
Элемент - дата

Назыать блок блоком странно
Мы же не говорим Человек Александр, мы говорим Александр
В данном случае написано что-то не совсем понятно
Блок инпут у него есть элемент оберткаБлок, у которого элемент полевводаДата

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +    [styles.blockWrapper__inputDate]: true,
[styles.inputDate]: true,
    [styles.blockWrapper__inputDate]: true,

не стоит конкотенировать статику, только динамику

здесь достаточно без classnamees написать <div className={styles.input}>

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +    [styles.blockWrapper__inputDate]: true,
На самом верхнем уровне стоит подмешивать [classNames]: !!classNames

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +    [styles.input_locked]: isLocked,
предлагаю использовать кемелКейс нотацию

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +        {/* {isEmpty && ( */}
удалить закоментированный код

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +        Дата и время заказа
предлагаю вынести в пропс и задать значение по умолчанию
плохо, когда у общего компонента, который может исопльзоваться в разных частях проекта жестко зашито слово заказа

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +      <label className={classLabelInput} htmlFor="inputDate">
htmlFor нужно проверитть работает ли это в реакте
https://ru.reactjs.org/docs/dom-elements.html#htmlfor

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.jsx
> +            <Icons name="x-large" className={styles.iconX} />
заменить на свгр

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.module.css
> +  margin-bottom: 50px;
вся верстка должна быть кратна 4 и в ремах

2022-03-22 12:39 UTC, smakhnatkin commented on src/components/Input/Input.module.css
> +  padding: 4px 20px 4px 8px;
использй рем

2022-03-22 18:02 UTC, Muslik commented on src/components/Input/Input.jsx
> +      <label className={classLabelInput} htmlFor="inputDate">
Работает :)

2022-03-27 17:09 UTC, sponfin commented
Про то, что темы лучше предавать понял. Но прошу все сразу косяки выложить, чтобы я сразу все исправлял. 
Так все вроде работает, но пока реализовал так как смог...

2022-03-27 22:40 UTC, Muslik requested changes
Есть ошибка в консоли. Не вижу настроенного prettier. Кучу замечаний расписал

2022-03-27 22:40 UTC, Muslik commented on src/Icons/icons.svg
> +<svg width="0" height="0" class="hidden">
Зачем нужен этот файл?

2022-03-27 22:40 UTC, Muslik commented on src/Icons/icons.svg
> +<svg width="0" height="0" class="hidden">
Папки Icons должна называться с маленькой буквы

2022-03-27 22:40 UTC, Muslik commented on src/Icons/sprite.svg
> +<svg width="0" height="0" class="hidden">
Думаю он уже не нужен

2022-03-27 22:40 UTC, Muslik commented on src/css/Input.module.css
> +.block-wrapper__input-date {
Что это за файл. Что он тут делает

2022-03-27 22:40 UTC, Muslik commented on src/App.js
>        <div className="block-wrapper page__block-wrapper">
У вас дальше появятся еще фичи (Ваша таблица с заказами). Куда вы ее будете класть?
Я в телеграмме писал чтобы вы сделали отдельную папку с фичами, туда положили компонент UiKit.jsx, туда же стили UiKit.module.css

2022-03-27 22:40 UTC, Muslik commented on src/App.js
>          <p className="block-wrapper__title">Input-date</p>
Используем css модули

2022-03-27 22:40 UTC, Muslik commented on src/components/Button/Button.jsx
> +  const classThemeButton = cn(styles._, className, {
Уфф. Погнали :)
Тему, размер вы можете сделать вычисляемой на основе переданного значения.
```javascript
const buttonClass = cx(styles._, className, {
  [styles[`theme_${theme}`]]: true,
  [styles[`size_${size}`]]: true,
});
```

2022-03-27 22:40 UTC, Muslik commented on src/components/Button/Button.jsx
> +    [styles.size_largeSquare]: isSizeLargeSquare,
Не нужны отдельный классы для компонентов только с иконками. Вы вычислять их можете на основе параметров которые приходят.
```javascript
const buttonClass = cx(styles._, className, {
  [styles.iconOnly]: Icon && !children,
}
```

2022-03-27 22:40 UTC, Muslik commented on src/components/Button/Button.jsx
> +    [styles.sizeLargeIcon]: isSizeLarge,
Не нужны отдельный классы на иконке. Сделайте зависимость от размера кнопки.

2022-03-27 22:40 UTC, Muslik commented on src/components/Button/Button.jsx
> +  const classThemeButton = cn(styles._, className, {
Почему переменная называется classTheme если там еще и размер :)

```buttonClass```, ```classButton``` идеально сюда подходит

2022-03-27 22:40 UTC, Muslik commented on src/components/Button/Button.jsx
> +  isThemeBlack,
Просто один параметр темы

2022-03-27 22:40 UTC, Muslik commented on src/components/Button/Button.jsx
> +  isSizeLargeSquare,
Просто один параметр размера size

2022-03-27 22:40 UTC, Muslik commented on src/components/Checkbox/Checkbox.jsx
> +  type = 'checkbox',
Если компонент checkbox то type не может быть никаким другим. Значит нет смысла его принимать

2022-03-27 22:40 UTC, Muslik commented on src/components/Checkbox/Checkbox.jsx
> +
не нужна пустая строка

2022-03-27 22:40 UTC, Muslik commented on src/components/Checkbox/Checkbox.jsx
> +    <div className={classCheckboxGroup}>
По идее единственный стиль который вам нужно править это отступ от самого внешнего блока. Отступы между checkbox-ами не планируют меняться. Сам label по идее тоже. Можно оставить только className для внешнего блока

2022-03-27 22:40 UTC, Muslik commented on src/components/Checkbox/Checkbox.jsx
> +};
А теперь как можно сделать красивее. У вас label есть и в checkbox и radio.

Делаем отдельно два компонента: Radio, Checkbox

```javascript
<Radio />
<Checkbox />
```
И делаем отдельный компонент для Label (С ним можем использовать и Radio и Checkbox и может что то еще в дальнейшем.

Пример:
```javascript
const FormControlLabel = ({ control, label }) => {
  return (
    <label>
      {control}
      {label}
    </label>
  )
}

const App = () => {
  return (
    <div>
      <FormControlLabel control={<Checkbox defaultChecked />} label="Выбрать Checkbox" />
      <FormControlLabel control={<Radio />} label="Выбрать Radio" />
    </div>
  )
}
```

Таким образом мы получаем полностью независимые блоки. И мы можем изменить стиль label или radio не затрагивая сам блок

2022-03-27 22:40 UTC, Muslik commented on src/components/Checkbox/Checkbox.jsx
> +};
Плюс не нужен никакой id или htmlFor

2022-03-27 22:40 UTC, Muslik commented on src/components/Input/Input.jsx
> +  isLocked = false,
isLocked тоже самое что и isDisabled

2022-03-27 22:40 UTC, Muslik commented on src/components/Input/Input.jsx
> +  type = 'datetime',
Я бы тут оставил text как дефолтное значение.

2022-03-27 22:40 UTC, Muslik commented on src/components/Input/Input.jsx
> +        {isNotEmpty && (
isNotEmpty не должен приходить из пропсов. Он должен высчитываться на основе value

2022-03-27 22:40 UTC, Muslik commented on src/components/Input/Input.jsx
> +          <div className={styles.iconLocked}>
Этот стиль применяется к disabled input-у. Не нужен отдельный пропс isLocked для этого

2022-03-27 22:40 UTC, Muslik commented on src/components/Input/Input.jsx
> +        {view === 'search' && (
Вы используете Input и он почему то принимает какой то view. Я бы лучше обособился от search и вставил бы просто иконку.
Сделайте допустим props ```titleIcon``` и передавайте туда иконку нужную.

А если вы хотите сделать уже готовый компонент для поиска, то делаете компонент ```<Search />``` в который передадите сразу иконку ```<IconSearch />```

2022-03-27 22:40 UTC, Muslik commented on src/components/Checkbox/Checkbox.jsx
> +};
Называем FormControlLabel потому что такой label будет использоваться чисто для контроллов - checkbox, radio

2022-03-27 22:40 UTC, Muslik commented on src/components/Radio/Radio.jsx
> +      {isRadio && <span className={classCustomRadio}></span>}
isRadio. А чем еще может быть блок Radio ? :)

Я выше предлагал сделать вариант FormControlLabel. Передавайте туда пропс hideControl. И тогда иконка отображаться не будет

2022-03-27 22:40 UTC, Muslik commented on src/components/Label/Label.jsx
> +    <label className={classLabel} htmlFor={htmlFor}>
Опять же нужно передавать два параметра для того чтобы он работал. В Input id, сюда htmlFor.

Я бы создал обертку:
```javascript
<FormInputLabel input={<Input type="datetime" />} label="Мой чудесный инпут" />
```

И внутри label будет оборачивать input.

Ваш вариант ок и я его приму. Просто рассказываю как можно было бы сделать красивее. А такой блок как у вас не особо смысл имеет. Можно сразу тег вставить <label> и все

2022-03-27 22:40 UTC, Muslik commented on src/components/Radio/Radio.jsx
> +  classCustomRadioLoc,
Что такое Loc

2022-03-27 22:40 UTC, Muslik commented on src/components/Radio/Radio.jsx
> +      {isRadio && <span className={classCustomRadio}></span>}
Если вы предполагаете что можно прокидывать свои иконки, то сделайте два дополнительных пропса: icon и checkedIcon. И не нужен будет classCustomRadio. Вы в чекбоксе иконку передавали как ReactComponent, здесь как background-image. Думаю стоит и там и там выбрать первый вариант. И передав два пропса (icon, checkedIcon) вы можете поменять любую из них

2022-03-27 22:40 UTC, Muslik commented on src/App.js
> +          value="06.12.2021"
Не могу редактировать input. Используйте defaultValue вместо value

2022-03-27 22:40 UTC, Muslik commented on src/App.js
> +            classlabelLoc="labelLoc"
Все классы через css модули.

2022-03-27 22:40 UTC, Muslik commented on src/App.js
> +            classCustomCheckboxLoc="customCheckboxloc"
вам нужно передавать три класса для расширения стилизации обычного чекбокса. Что то не то :)

2022-03-27 22:40 UTC, Muslik commented on src/App.js
> +            htmlFor="checkbox2"
Вот почему стоит использовать отдельный блок для label. Внешнему пользователю непонятно для чего я передаю id и для него же htmlFor.

2022-03-28 22:53 UTC, Muslik commented on src/components/Button/Button.jsx
> +    [styles[`size_${size}Square`]]: Icon && !children,
Тут size уже не нужен.
Просто ```styles.iconOnly```, затем в css ->
```css
.size_medium. .iconOnly {}
.size_small .iconOnly {}
```

2022-03-28 22:54 UTC, Muslik commented on src/components/Button/Button.jsx
> +    [styles.sizeSmallIcon]: size === "small" && children,
У иконки всегда одинаковый размер.

2022-03-28 22:55 UTC, Muslik commented on src/components/Button/Button.jsx
> +    [styles.sizeSmallIcon]: size === "small" && children,
И даже если размер будет другой, мы зависим от размера кнопки:
```css
.size_medium .icon { width: 24px; height: 24px }
.size_small .icon { width: 16px; height: 16px }
```

2022-03-28 22:57 UTC, Muslik commented on src/modules/UiKit/UiKit.jsx
> +import "./uikit.css";
```javascript
import styles from './uiKit.module.css
```

2022-03-30 08:37 UTC, sponfin commented on src/Icons/icons.svg
> +<svg width="0" height="0" class="hidden">
Fixed

2022-03-30 08:38 UTC, sponfin commented on src/Icons/sprite.svg
> +<svg width="0" height="0" class="hidden">
Fixed

2022-03-30 08:38 UTC, sponfin commented on src/css/Input.module.css
> +.block-wrapper__input-date {
Fixed

2022-03-30 08:39 UTC, sponfin commented on src/components/Button/Button.jsx
> +  const classThemeButton = cn(styles._, className, {
Fixed

2022-03-30 08:39 UTC, sponfin commented on src/components/Button/Button.jsx
> +    [styles.size_largeSquare]: isSizeLargeSquare,
Fixed

2022-03-30 08:39 UTC, sponfin commented on src/components/Button/Button.jsx
> +    [styles.sizeLargeIcon]: isSizeLarge,
Fixed

2022-03-30 08:39 UTC, sponfin commented on src/components/Button/Button.jsx
> +  isThemeBlack,
Fixed

2022-03-30 08:39 UTC, sponfin commented on src/components/Button/Button.jsx
> +  isSizeLargeSquare,
Fixed

2022-03-30 08:41 UTC, sponfin commented on src/App.js
> +            classlabelLoc="labelLoc"
Fixed

2022-03-30 08:42 UTC, sponfin commented on src/components/Button/Button.jsx
> +    [styles.sizeSmallIcon]: size === "small" && children,
Fixed

2022-03-30 08:42 UTC, sponfin commented on src/modules/UiKit/UiKit.jsx
> +import "./uikit.css";
Fixed

2022-03-31 20:00 UTC, sponfin commented on src/components/Checkbox/Checkbox.jsx
> +  type = 'checkbox',
Fixed

2022-03-31 20:00 UTC, sponfin commented on src/components/Checkbox/Checkbox.jsx
> +
Fixed

2022-03-31 20:02 UTC, sponfin commented on src/components/Input/Input.jsx
> +  type = 'datetime',
fixed

2022-03-31 20:03 UTC, sponfin commented on src/components/Label/Label.jsx
> +    <label className={classLabel} htmlFor={htmlFor}>
Fixed

2022-03-31 20:03 UTC, sponfin commented on src/components/Radio/Radio.jsx
> +  classCustomRadioLoc,
Fixed

2022-03-31 20:04 UTC, sponfin commented on src/App.js
> +            classCustomCheckboxLoc="customCheckboxloc"
Fixed

2022-03-31 20:04 UTC, sponfin commented on src/App.js
> +            htmlFor="checkbox2"
Fixed

2022-03-31 20:04 UTC, sponfin commented on src/components/Button/Button.jsx
> +    [styles[`size_${size}Square`]]: Icon && !children,
Fixed

2022-03-31 20:09 UTC, sponfin commented on src/components/Input/Input.jsx
> +          <div className={styles.iconLocked}>
Fixed

2022-03-31 20:15 UTC, sponfin commented on src/components/Input/Input.jsx
> +  isLocked = false,
Fixed

2022-03-31 20:16 UTC, sponfin commented on src/App.js
>        <div className="block-wrapper page__block-wrapper">
Fixed

2022-03-31 20:17 UTC, sponfin commented on src/App.js
>          <p className="block-wrapper__title">Input-date</p>
Fixed

2022-03-31 20:28 UTC, sponfin commented on src/components/Checkbox/Checkbox.jsx
> +    <div className={classCheckboxGroup}>
Fixed.
Использую два класса для универсализации. Один отступы между чекбоксами, второй отступ label

2022-04-01 16:26 UTC, sponfin commented on src/components/Checkbox/Checkbox.jsx
> +};
Fixed

2022-04-01 16:26 UTC, sponfin commented on src/components/Input/Input.jsx
> +        {isNotEmpty && (
Fixed

2022-04-01 17:16 UTC, sponfin commented
Вроде все "причесал". Пока Dropdown оставил без изменения цвета у Label. Буду дальше со стейтами разбираться...

2022-04-03 14:42 UTC, Muslik requested changes

2022-04-03 14:42 UTC, Muslik commented on src/components/Input/Input.jsx
> +  isDisabled = false,
У инпута есть свойство disabled. Используйте его

2022-04-03 14:42 UTC, Muslik commented on src/components/Input/Input.jsx
> +  iconClear: IconClear,
iconClear зашита в инпуте. Не нужно ее кастомизировать. Поэтому не нужны такие пропсы

2022-04-03 14:42 UTC, Muslik commented on src/components/Input/Input.jsx
> +  iconLocked: IconLocked,
Тоже самое. Она всегда будет такой. Если она изменится, изменится сразу во всех инпутах

2022-04-03 14:42 UTC, Muslik commented on src/components/Radio/Radio.jsx
> +import styles from "./Rdio.module.css";
Rdio -> Radio

2022-04-03 14:42 UTC, Muslik commented on src/components/Radio/Radio.jsx
> +  const classRadio = cn(styles._, className);
nit: такие маленькие классы можно сразу прокидывать:
```javascript
<div className={cn(styles._, className)}>
```

2022-04-03 14:42 UTC, Muslik commented on src/components/Checkbox/Checkbox.jsx
> +  ...props
Эти пропсы нужно прокинуть дальше.

```javascript
<input type="checkbox" {...props} />
```

2022-04-03 14:42 UTC, Muslik commented on src/components/ControlLabel/ControlLabel.jsx
> +  classControllLabel,
Переименовать:

classControllLabel -> labelClassName
classControl -> className

2022-04-03 14:42 UTC, Muslik commented on src/components/Radio/Radio.jsx
> +      {!isNoRadio && <span className={styles.customRadio}></span>}
Я бы переименовал в hasIcon. В деструктуризации выше поставил бы true как значение по умолчанию

И тогда получится красиво: ```{hasIcon && <span>}``` - есть иконка -> рисуем
В вашем случае получается: Если нет нет radio -> рисуем. 

Поэтому стоит брать положительный вариант и его отрицать:

disabled -> !disabled
valid -> !valid
hasIcon -> !hasIcon

2022-04-03 14:42 UTC, Muslik commented on src/modules/UiKit/UiKit.jsx
> +              <ControlLabel
Вот тут не нужно делать отступ для label если у Radio есть пропс ```hasIcon={false}```

Поэтому внутри ControlLabel нужно сделать проверку:

```javascript
className={cx(styles._, {[styles.noIcon]: !control.props.hasIcon })}
```

2022-04-03 14:42 UTC, Muslik commented on src/components/Input/Input.jsx
> +          disabled={isDisabled}
Цвет текста у disabled инпута не такой как на макете

2022-04-03 14:57 UTC, sponfin commented on src/components/Input/Input.jsx
> +  isDisabled = false,
Fixed

2022-04-03 14:58 UTC, sponfin commented on src/components/Radio/Radio.jsx
> +import styles from "./Rdio.module.css";
Fixed

2022-04-03 15:02 UTC, sponfin commented on src/components/Input/Input.jsx
> +  iconClear: IconClear,
Fixed

2022-04-03 15:02 UTC, sponfin commented on src/components/Input/Input.jsx
> +  iconLocked: IconLocked,
Fixed

2022-04-03 15:03 UTC, sponfin commented on src/components/Radio/Radio.jsx
> +  const classRadio = cn(styles._, className);
Fixed

2022-04-03 15:14 UTC, sponfin commented on src/components/Input/Input.jsx
> +          disabled={isDisabled}
Fixed

2022-04-03 15:20 UTC, sponfin commented on src/components/Checkbox/Checkbox.jsx
> +  ...props
Fixed

2022-04-03 15:38 UTC, sponfin commented on src/components/ControlLabel/ControlLabel.jsx
> +  classControllLabel,
Fixed

2022-04-03 15:44 UTC, sponfin commented on src/components/Radio/Radio.jsx
> +      {!isNoRadio && <span className={styles.customRadio}></span>}
Fixed

2022-04-03 16:20 UTC, sponfin commented on src/modules/UiKit/UiKit.jsx
> +              <ControlLabel
Fixed

2022-04-03 17:06 UTC, Muslik approved these changes
Well done

2022-04-03 17:46 UTC, merged